# REPOSITORY NAME (c) by the University of Piraues, Greece.
#
# REPOSITORY NAME is licensed under a
# Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#
# You should have received a copy of the license along with this
# work.  If not, see <http://creativecommons.org/licenses/by-nc-nd/3.0/>.

import json
import pandas as pd

# Function to create a distance matrix from a JSON input.
#
# Parameters:
# - input_data: JSON file path (str) or a dictionary containing the input data.
# - large_number: Value to replace NaN entries in the matrix for non-existent connections.
#
# Returns:
# - a_to_b_matrix: DataFrame representing distances between nodes in a bipartite graph.
def create_distance_matrices(input_data, large_number=1000000):
    if isinstance(input_data, str):
        with open(input_data, 'r') as f:
            input_data = json.load(f)
    elif isinstance(input_data, dict):
        input_data = input_data  # If it's already a dict (e.g., from Postman), use it directly
    else:
        raise ValueError("Input data should be either a valid file path or a dictionary.")

    # Extract the distance matrix from the input data
    distance_matrix = input_data['data']['distanceMatrix']

    # Dictionary to store parsed distances between nodes
    a_to_b_data = {}

    # Iterate over each entry in the distance matrix
    for entry in distance_matrix:
        # Extract the route (e.g., "(A, B)") and distance
        edge = entry.get('edge')
        if edge:
            # Parse the nodes from the edge string (e.g., "A" and "B" from "(A, B)")
            pointA, pointB = edge.strip('()').split(', ')

            # Extract the distance
            distance = entry['distance']

            # Add the distances from pointA to pointB
            if pointB not in a_to_b_data:
                a_to_b_data[pointB] = {}
            a_to_b_data[pointB][pointA] = distance  # Reverse direction for distance matrix

    # Create a DataFrame for the distance matrix
    a_to_b_matrix = pd.DataFrame(a_to_b_data)

    # Fill NaN values with the large number (for non-existing connections)
    a_to_b_matrix = a_to_b_matrix.fillna(large_number).astype('int64')

    # Handle node ordering: treat 0.0 as a kit holder and 0.0.0 as a gravity rack
    kit_holders = sorted([node for node in a_to_b_matrix.index if len(node.split('.')) == 2 or node == '0.0'])
    gravity_racks = sorted([node for node in a_to_b_matrix.index if len(node.split('.')) == 3 or node == '0.0.0'])

    # Combine the node order: first kit holders, then gravity racks
    node_order = kit_holders + gravity_racks

    # Reindex rows and columns based on the combined node order
    a_to_b_matrix = a_to_b_matrix.reindex(index=node_order, columns=node_order, fill_value=large_number)

    # Return the finalized distance matrix
    return a_to_b_matrix

def tsplib_to_json(tsp_path):
    """
    Parse a TSPLIB .tsp file (FULL_MATRIX format) generated by
    convert_to_tsplib.py and convert it to the internal JSON format
    expected by run_tsp().

    Node order assumed: depot(0.0), GR nodes, KH nodes, end(0.0.0)
    as written by convert_to_tsplib.py.
    """
    with open(tsp_path) as f:
        lines = [l.strip() for l in f.readlines()]

    # Parse header
    header = {}
    matrix_start = 0
    for i, line in enumerate(lines):
        if line == 'EDGE_WEIGHT_SECTION':
            matrix_start = i + 1
            break
        if ':' in line:
            key, val = line.split(':', 1)
            header[key.strip()] = val.strip()

    n = int(header['DIMENSION'])

    # Parse comment to get |A| and |B|
    # COMMENT: BTSP instance |A|=10 GR nodes |B|=10 KH nodes ...
    comment = header.get('COMMENT', '')
    import re
    a_match = re.search(r'\|A\|=(\d+)', comment)
    b_match = re.search(r'\|B\|=(\d+)', comment)
    n_gr = int(a_match.group(1)) if a_match else None
    n_kh = int(b_match.group(1)) if b_match else None

    if n_gr is None or n_kh is None:
        raise ValueError("Cannot determine |A| and |B| from COMMENT line.")
    if n_gr + n_kh + 2 != n:
        raise ValueError(f"DIMENSION {n} does not match |A|+|B|+2 = {n_gr+n_kh+2}")

    # Reconstruct node list in the same order as convert_to_tsplib.py
    # [0.0, GR_1..GR_n, KH_1..KH_m, 0.0.0]
    # We don't know original node names so we reconstruct generic ones
    # that match the naming convention used in the pipeline
    node_names = ['0.0']
    for i in range(n_gr):
        node_names.append(f'1.1.{i+1}')   # generic GR names
    for i in range(n_kh):
        node_names.append(f'1.{i+1}')     # generic KH names
    node_names.append('0.0.0')

    # Parse matrix
    matrix_lines = []
    for line in lines[matrix_start:]:
        if line == 'EOF':
            break
        matrix_lines.append(list(map(int, line.split())))

    LARGE = 999999

    # Build distance matrix entries (skip 999999 = non-existent edges)
    distance_matrix = []
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            dist = matrix_lines[i][j]
            if dist < LARGE:
                distance_matrix.append({
                    "edge": f"({node_names[i]}, {node_names[j]})",
                    "distance": dist
                })

    return {
        "route": "robot-pick-seq-opt",
        "uuid": tsp_path,
        "generated_at": 0,
        "data": {
            "method": "all",
            "start_node": "0.0",
            "end_node": "0.0.0",
            "distanceMatrix": distance_matrix
        }
    }


def load_instance(file_path):
    """
    Load either a JSON or TSPLIB (.tsp) instance file.
    Returns the internal JSON dict expected by run_tsp().
    """
    if file_path.endswith('.tsp'):
        return tsplib_to_json(file_path)
    else:
        import json
        with open(file_path) as f:
            return json.load(f)